# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 18:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('license_number', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{1,6}$', 'License number may only consists of maximum 6 figures!')])),
                ('color_belt', models.CharField(choices=[('0e Kyu', 'Witte gordel'), ('0e Kyu', 'Witte gordel met groen streepje'), ('0e Kyu', 'Witte gordel met twee groene streepjes'), ('9e Kyu', 'Witte gordel met zwart streepje'), ('9e Kyu', 'Rode gordel'), ('8e Kyu', 'Gele gordel'), ('7e Kyu', 'Oranje gordel'), ('6e Kyu', 'Groene gordel'), ('5e Kyu', 'Blauwe gordel'), ('4e Kyu', 'Blauwe gordel met wit streepje'), ('3e Kyu', 'Bruine gordel'), ('2e Kyu', 'Bruine gordel met wit streepje'), ('1e Kyu', 'Bruine gordel met twee witte streepjes')], max_length=6)),
            ],
        ),
    ]
