# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 18:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_participants', models.CharField(choices=[('Beginners', 'Beginners'), ('Advanced', 'Gevorderden'), ('Kids', 'Kinderen'), ('Youth', 'Jeugd')], max_length=20)),
                ('examination_type', models.CharField(choices=[('Form', 'Vorm'), ('Rhytm', 'Ritme'), ('Official', 'Officieel')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('gsm', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^04[0-9]{8}$', 'GSM number must consists of 10 numbers and it must start with a 0!')])),
                ('email', models.EmailField(max_length=254)),
                ('license_number', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{1,6}$', 'License number may only consists of maximum 6 figures!')])),
                ('grade', models.CharField(choices=[('0e Kyu', 'Witte gordel'), ('9e Kyu', 'Witte gordel met zwart streepje'), ('9e Kyu', 'Rode gordel'), ('8e Kyu', 'Gele gordel'), ('7e Kyu', 'Oranje gordel'), ('6e Kyu', 'Groene gordel'), ('5e Kyu', 'Blauwe gordel'), ('4e Kyu', 'Blauwe gordel met wit streepje'), ('3e Kyu', 'Bruine gordel'), ('2e Kyu', 'Bruine gordel met wit streepje'), ('1e Kyu', 'Bruine gordel met twee witte streepjes')], max_length=6)),
                ('number_of_red_ribbons', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2')])),
                ('age', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[0-9]{1,2}$', 'Age must consists of a numerical value of maximum 2 figures!')])),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Subscription.Category')),
            ],
        ),
    ]
