# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Subscription.Category'),
        ),
    ]
