# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 15:56
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='date_till_license_is_valid',
            field=models.DateField(default=datetime.datetime(2016, 4, 2, 15, 56, 20, 516761, tzinfo=utc), verbose_name='Licentie geldigheids datum'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='age',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[0-9]{1,2}$', 'Leeftijd moet bestaan uit maximum 2 cijfers!')], verbose_name='Leeftijd'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Voornaam'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='grade',
            field=models.CharField(choices=[('0e Kyu', 'Witte gordel'), ('9e Kyu', 'Witte gordel met zwart streepje'), ('9e Kyu', 'Rode gordel'), ('8e Kyu', 'Gele gordel'), ('7e Kyu', 'Oranje gordel'), ('6e Kyu', 'Groene gordel'), ('5e Kyu', 'Blauwe gordel'), ('4e Kyu', 'Blauwe gordel met wit streepje'), ('3e Kyu', 'Bruine gordel'), ('2e Kyu', 'Bruine gordel met wit streepje')], max_length=6, verbose_name='Graad'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gsm',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^04[0-9]{8}$', 'GSM nummer moet bestaan uit 10 nummers en het moet starten met 04!')], verbose_name='Gsm'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Naam'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='license_number',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{1,6}$', 'Licentie nummer mag enkel bestaan uit maximum 6 cijfers!')], verbose_name='Licentienummer'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='number_of_red_ribbons',
            field=models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2')], verbose_name='Aantal rode lintjes'),
        ),
    ]
