# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='number_of_red_ribbons',
            field=models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2')], default=0),
        ),
    ]
