# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0003_participant_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Beginners', 'Beginners'), ('Gevorderden', 'Advanced'), ('Kinderen', 'Kids'), ('Jeugd', 'Youth')], max_length=20)),
                ('examination_type', models.CharField(choices=[('Vorm', 'Form'), ('Ritme', 'Rhytm'), ('Officieel', 'Official')], max_length=10)),
            ],
        ),
    ]
