# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0005_auto_20160306_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type_of_competitors',
            field=models.CharField(choices=[('Beginners', 'Beginners'), ('Advanced', 'Gevorderden'), ('Kids', 'Kinderen'), ('Youth', 'Jeugd')], max_length=20),
        ),
    ]
